### ISSUE TITLE
Add ability to send the "typing" event in the outcomes array. 

### ISSUE THREAD

**Issue by dharmeshs** [slackapi/python-rtmbot#56]
Right now, we can send DM messages back to the user.

But, it would be nice to be able post a "typing" event (indicating that the bot is typing). This gives users comfort, particularly when processing the message might take a little while.

The event structure (from the Slack API docs):

{
    "id": 1,
    "type": "typing",
    "channel": "C024BE91L"
}

So, similar to sending a DM, but just a different JSON structure needs to be sent.

**Comment by himanshu81494** [comment]
I think it is like:
`{
"type" : "user_typing",
"channel": "C034RYTR5",
"user": "U674BETY"
}`

The 'user_typing' event is sent to all members of a channel when a user is typing a message in that channel.
