### ISSUE TITLE
rtmbot does not handle websocket disconnections (incl team_migration_starting)

### ISSUE THREAD

**Issue by devkev** [slackapi/python-rtmbot#74]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

As per https://api.slack.com/events/team_migration_started, when this event occurs all websockets will be closed.  This causes an exception inside `rtm_read()`, which is not handled by `_start()`, `start()`, or `main()`, meaning that the rtmbot will exit with an unhandled exception.

Ideally the bot should catch such exceptions and react accordingly, eg. by reconnecting and then continuing to process rtm events.

#### Reproducible in:
* [ ] This is reproducible in the sample project.
RTMBot version:
Python version:
OS Version:

#### Steps to reproduce:

I haven't actually done this in rtmbot, but I have seen it in extremely similar code.

1. Start rtmbot
2. Verify that it is processing rtm events
3. Use a utility like `tcpkill` to reset the rtm websocket connection (use `netstat` to find the connection)

### Expected result:
rtmbot reconnects and continues

### Actual result:
rtmbot exits with an unhandled exception

### Attachments:
> e.g. Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by Roach** [comment]
This was fixed in python slackclient 1.2.0
