### ISSUE TITLE
References to CODE_OF_CONDUCT.md in .github directory

### ISSUE THREAD

**Issue by todofixthis** [slackapi/python-rtmbot#77]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
On https://github.com/slackhq/python-rtmbot/blob/master/.github/CONTRIBUTING.md in the Before Contributing section, there is a link to CODE_OF_CONDUCT.md:

> Before contributing, please read our [Code of Conduct](./CODE_OF_CONDUCT.md). We take it very seriously, and expect that you will as well.

The actual link goes to this URL:  
<https://github.com/slackhq/python-rtmbot/blob/master/.github/CODE_OF_CONDUCT.md>

However, it appears that this file has been moved to the top level of the project:  
<https://github.com/slackhq/python-rtmbot/blob/master/CODE_OF_CONDUCT.md>

I'm not sure whether the file should be moved back into the .github directory, or if the links in the CONTRIBUTING.md and issue/PR templates need to be updated, so I just opened an issue instead.

**Comment by Roach** [comment]
Thanks for bringing this up. Fixed it 👍
