### ISSUE TITLE
Enable python-rtmbot to work from behind a Proxy.

### ISSUE THREAD

**Issue by pvs13102012** [slackapi/python-rtmbot#86]
* [x] I've read and understood the Contributing guidelines and have done my best effort to follow them.
* [x] I've read and agree to the Code of Conduct.
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
> I want to deploy my slack bot from behind a personal proxy but I suppose this cannot be done since proxy requires authentication
> I couldn't find any documentation to run the slack bot from behind a proxy. 
> Appreciate if you guys can help fix this. 

#### Reproducible in:
* [x] This is reproducible in the sample project.
RTMBot version: Latest
Python version: 2.7
OS Version: Any

**Comment by Roach** [comment]
We added proxy support to `slackclient` last june (https://github.com/slackapi/python-slackclient/commit/79ca0cbdbbfe12b24c1e9b187ed591aad7a17a58), but it looks like this library doesn't allow options to be passed all the way through...

**Comment by Roach** [comment]
Will be resolved with #89
